# Generated by Django 3.1.5 on 2021-01-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_band_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
